server:
  port: 8007
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.wcan.scms.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
spring:
  application:
    name: scms-hystrix-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud_db_three
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8002/eureka